version: '3.8'

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: microblog-swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/swagger.yaml
    volumes:
      - ./swagger.yaml:/swagger.yaml:ro
    networks:
      - microblog-docs

  redoc:
    image: redocly/redoc:latest
    container_name: microblog-redoc
    ports:
      - "8081:80"
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml:ro
    command: >
      sh -c "
        echo 'server {
          listen 80;
          location / {
            root /usr/share/nginx/html;
            try_files \$uri \$uri/ /index.html;
          }
          location /swagger.yaml {
            root /usr/share/nginx/html;
          }
        }' > /etc/nginx/conf.d/default.conf &&
        nginx -g 'daemon off;'
      "
    networks:
      - microblog-docs

  swagger-editor:
    image: swaggerapi/swagger-editor:latest
    container_name: microblog-swagger-editor
    ports:
      - "8082:8080"
    volumes:
      - ./swagger.yaml:/swagger.yaml:ro
    environment:
      - SWAGGER_FILE=/swagger.yaml
    networks:
      - microblog-docs

  nginx:
    image: nginx:alpine
    container_name: microblog-docs-nginx
    ports:
      - "8083:80"
    volumes:
      - ./swagger.yaml:/usr/share/nginx/html/swagger.yaml:ro
      - ./swagger-ui.html:/usr/share/nginx/html/index.html:ro
      - ./redoc.html:/usr/share/nginx/html/redoc.html:ro
    networks:
      - microblog-docs

networks:
  microblog-docs:
    driver: bridge
